# Generated by Django 5.0.2 on 2024-02-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15)),
                ('otp', models.IntegerField(max_length=6)),
                ('validate_type', models.CharField(choices=[('SIGNUP', 'Signup'), ('LOGIN', 'Login'), ('FORGET_PASSWORD', 'ForgetPassword')], default='SIGNUP', max_length=20)),
                ('otp_expires', models.DateTimeField()),
            ],
        ),
    ]
